//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 12:55:41 AM BRST 
//


package br.ufrgs.inf.ras.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * An ArtifactDependency identifies a dependent Artifact.  The dependent Artifact must be another Artifact defined in the manifest.  See the Artifact description. This is a child element to the Artifact element. The dependencyType attribute describes artifact dependencies such as design time dependency or a compile time or runtime.
 * 
 * <p>Java class for ArtifactDependency complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ArtifactDependency">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dependencyKind" type="{http://defaultprofile.ecore}DependencyKind"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dependencyType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="artifact" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ArtifactDependency", propOrder = {
    "dependencyKind"
})
@XmlRootElement(name = "ArtifactDependency")
public class ArtifactDependency {

    @XmlElement(required = true)
    protected DependencyKind dependencyKind;
    @XmlAttribute
    protected String dependencyType;
    @XmlAttribute
    protected String artifact;

    /**
     * Gets the value of the dependencyKind property.
     * 
     * @return
     *     possible object is
     *     {@link DependencyKind }
     *     
     */
    public DependencyKind getDependencyKind() {
        return dependencyKind;
    }

    /**
     * Sets the value of the dependencyKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependencyKind }
     *     
     */
    public void setDependencyKind(DependencyKind value) {
        this.dependencyKind = value;
    }

    /**
     * Gets the value of the dependencyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDependencyType() {
        return dependencyType;
    }

    /**
     * Sets the value of the dependencyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDependencyType(String value) {
        this.dependencyType = value;
    }

    /**
     * Gets the value of the artifact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtifact() {
        return artifact;
    }

    /**
     * Sets the value of the artifact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtifact(String value) {
        this.artifact = value;
    }

}
