//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 12:55:41 AM BRST 
//


package br.ufrgs.inf.ras.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

import org.eclipse.core.runtime.ListenerList;


/**
 * xmi:ordered=true
 * 
 * property order is (these are role names)
 *  1. description
 *  2. descriptor
 * 
 * A descriptor group is simply a container for a related group of <descriptor>s. A <description> child element can be used to provide a description of the descriptor group.
 * 
 * <p>Java class for DescriptorGroup complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescriptorGroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://defaultprofile.ecore}Description" minOccurs="0"/>
 *         &lt;element name="contained" type="{http://defaultprofile.ecore}DescriptorGroup" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="freeFormValue" type="{http://defaultprofile.ecore}FreeFormValue" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="freeFormDescriptor" type="{http://defaultprofile.ecore}FreeFormDescriptor" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="artifact" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="nodeDescriptor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="classificationSchema" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescriptorGroup", propOrder = {
    "description",
    "containeds",
    "freeFormValues",
    "freeFormDescriptors"
})
@XmlRootElement(name = "DescriptorGroup")
public class DescriptorGroup {

    protected Description description;
    @XmlElement(name = "contained")
    protected List<DescriptorGroup> containeds;
    @XmlElement(name = "freeFormValue")
    protected List<FreeFormValue> freeFormValues;
    @XmlElement(name = "freeFormDescriptor")
    protected List<FreeFormDescriptor> freeFormDescriptors;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String artifact;
    @XmlAttribute
    protected String nodeDescriptor;
    @XmlAttribute
    protected String classificationSchema;
    @XmlTransient
    private ListenerList listeners;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
        firePropertyChange();
    }

    /**
     * Gets the value of the containeds property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containeds property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContaineds().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptorGroup }
     * 
     * 
     */
    public List<DescriptorGroup> getContaineds() {
        if (containeds == null) {
            containeds = new ArrayList<DescriptorGroup>();
        }
        return this.containeds;
    }

    /**
     * Gets the value of the freeFormValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freeFormValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreeFormValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FreeFormValue }
     * 
     * 
     */
    public List<FreeFormValue> getFreeFormValues() {
        if (freeFormValues == null) {
            freeFormValues = new ArrayList<FreeFormValue>();
        }
        return this.freeFormValues;
    }

    /**
     * Gets the value of the freeFormDescriptors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the freeFormDescriptors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFreeFormDescriptors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FreeFormDescriptor }
     * 
     * 
     */
    public List<FreeFormDescriptor> getFreeFormDescriptors() {
        if (freeFormDescriptors == null) {
            freeFormDescriptors = new ArrayList<FreeFormDescriptor>();
        }
        return this.freeFormDescriptors;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
        firePropertyChange();
    }

    /**
     * Gets the value of the artifact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtifact() {
        return artifact;
    }

    /**
     * Sets the value of the artifact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtifact(String value) {
        this.artifact = value;
        firePropertyChange();
    }

    /**
     * Gets the value of the nodeDescriptor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeDescriptor() {
        return nodeDescriptor;
    }

    /**
     * Sets the value of the nodeDescriptor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeDescriptor(String value) {
        this.nodeDescriptor = value;
    }

    /**
     * Gets the value of the classificationSchema property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationSchema() {
        return classificationSchema;
    }

    /**
     * Sets the value of the classificationSchema property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationSchema(String value) {
        this.classificationSchema = value;
        firePropertyChange();
    }

    public void addListener(IListener listener) {
        if (listeners == null) {
            listeners = new ListenerList();
        }
        listeners.add(listener);
    }

    public void removeListener(IListener listener) {
        if (listeners != null) {
            listeners.remove(listener);
            if (listeners.isEmpty()) {
                listeners = null;
            }
        }
    }

    private void firePropertyChange() {
        if (listeners != null) {
            for (Object listener : listeners.getListeners()) {
                ((IListener) listener).objectChanged();
            }
        }
    }
}
