//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 12:55:41 AM BRST 
//


package br.ufrgs.inf.ras.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * xmi:contentType=mixed
 * 
 * A <descriptor> is a simple key/value pair that emphasizes certain qualities and characteristics of the asset. Often these are searchable and may be used for asset discovery and evaluation.
 * 
 * The value is captured as the elements content in plain text. A <descriptor> may be associated with a specific <context> through the context association.  This means that the key and value should be thought of in the specified <context>.  The value of the context association must reference an existing id of a <context> element.
 * 
 * <p>Java class for FreeFormDescriptor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FreeFormDescriptor">
 *   &lt;complexContent>
 *     &lt;extension base="{http://defaultprofile.ecore}Descriptor">
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FreeFormDescriptor")
@XmlRootElement(name = "FreeFormDescriptor")
public class FreeFormDescriptor
    extends Descriptor
{


}
