//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 12:55:41 AM BRST 
//


package br.ufrgs.inf.ras.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the br.ufrgs.inf.ras.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: br.ufrgs.inf.ras.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link ActivityParameter }
     * 
     */
    public ActivityParameter createActivityParameter() {
        return new ActivityParameter();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link RelatedProfile }
     * 
     */
    public RelatedProfile createRelatedProfile() {
        return new RelatedProfile();
    }

    /**
     * Create an instance of {@link FreeFormDescriptor }
     * 
     */
    public FreeFormDescriptor createFreeFormDescriptor() {
        return new FreeFormDescriptor();
    }

    /**
     * Create an instance of {@link Profile }
     * 
     */
    public Profile createProfile() {
        return new Profile();
    }

    /**
     * Create an instance of {@link DescriptorGroup }
     * 
     */
    public DescriptorGroup createDescriptorGroup() {
        return new DescriptorGroup();
    }

    /**
     * Create an instance of {@link Asset }
     * 
     */
    public Asset createAsset() {
        return new Asset();
    }

    /**
     * Create an instance of {@link Solution }
     * 
     */
    public Solution createSolution() {
        return new Solution();
    }

    /**
     * Create an instance of {@link ArtifactActivity }
     * 
     */
    public ArtifactActivity createArtifactActivity() {
        return new ArtifactActivity();
    }

    /**
     * Create an instance of {@link RelatedAsset }
     * 
     */
    public RelatedAsset createRelatedAsset() {
        return new RelatedAsset();
    }

    /**
     * Create an instance of {@link Activity }
     * 
     */
    public Activity createActivity() {
        return new Activity();
    }

    /**
     * Create an instance of {@link NodeDescriptor }
     * 
     */
    public NodeDescriptor createNodeDescriptor() {
        return new NodeDescriptor();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link ArtifactDependency }
     * 
     */
    public ArtifactDependency createArtifactDependency() {
        return new ArtifactDependency();
    }

    /**
     * Create an instance of {@link DependencyKind }
     * 
     */
    public DependencyKind createDependencyKind() {
        return new DependencyKind();
    }

    /**
     * Create an instance of {@link Usage }
     * 
     */
    public Usage createUsage() {
        return new Usage();
    }

    /**
     * Create an instance of {@link ArtifactContext }
     * 
     */
    public ArtifactContext createArtifactContext() {
        return new ArtifactContext();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link VariabilityPointBinding }
     * 
     */
    public VariabilityPointBinding createVariabilityPointBinding() {
        return new VariabilityPointBinding();
    }

    /**
     * Create an instance of {@link Descriptor }
     * 
     */
    public Descriptor createDescriptor() {
        return new Descriptor();
    }

    /**
     * Create an instance of {@link ReferenceKind }
     * 
     */
    public ReferenceKind createReferenceKind() {
        return new ReferenceKind();
    }

    /**
     * Create an instance of {@link ArtifactType }
     * 
     */
    public ArtifactType createArtifactType() {
        return new ArtifactType();
    }

    /**
     * Create an instance of {@link AssetActivity }
     * 
     */
    public AssetActivity createAssetActivity() {
        return new AssetActivity();
    }

    /**
     * Create an instance of {@link VariabilityPoint }
     * 
     */
    public VariabilityPoint createVariabilityPoint() {
        return new VariabilityPoint();
    }

    /**
     * Create an instance of {@link ContextRef }
     * 
     */
    public ContextRef createContextRef() {
        return new ContextRef();
    }

    /**
     * Create an instance of {@link FreeFormValue }
     * 
     */
    public FreeFormValue createFreeFormValue() {
        return new FreeFormValue();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link ClassificationSchema }
     * 
     */
    public ClassificationSchema createClassificationSchema() {
        return new ClassificationSchema();
    }

}
