//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 12:55:41 AM BRST 
//


package br.ufrgs.inf.ras.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * xmi:ordered=true
 * 
 * property order is (these are role names)
 *  1. description
 *  2. artifactContext
 *  3. artifactDependency
 *  4. variabilityPoint
 *  5. artifactType
 *  6. artifact
 * 
 * An artifact is a work product that can be created, stored and manipulated by asset producers/consumers and by tools. An artifact is either an actual file located in the asset's package, or represents a logical entity that contains at least one child artifact that is an actual file.  An <artifact> element must specify minimally a name or a reference attribute.  The name is required for artifacts that represent logical entities.  The reference is required for artifacts that specify actual file or work products that are part of the asset's packaging.
 * 
 * An artifact may specify child artifacts.  A child artifact uses the same <artifact> element.  If the artifact is a logical artifact then it must specify a name and have at least one descendent artifact that is an actual file reference.
 * 
 * <p>Java class for Artifact complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Artifact">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="artifactContext" type="{http://defaultprofile.ecore}ArtifactContext" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="artifactDependency" type="{http://defaultprofile.ecore}ArtifactDependency" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="artifact" type="{http://defaultprofile.ecore}Artifact" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="variabilityPoint" type="{http://defaultprofile.ecore}VariabilityPoint" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="description" type="{http://defaultprofile.ecore}Description" minOccurs="0"/>
 *         &lt;element name="artifactType" type="{http://defaultprofile.ecore}ArtifactType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reference" type="{http://defaultprofile.ecore}Reference" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="digestName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="digestValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="accessRights" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Artifact", propOrder = {
    "artifactContexts",
    "artifactDependencies",
    "artifacts",
    "variabilityPoints",
    "description",
    "artifactTypes",
    "reference"
})
@XmlRootElement(name = "Artifact")
public class Artifact {

    @XmlElement(name = "artifactContext")
    protected List<ArtifactContext> artifactContexts;
    @XmlElement(name = "artifactDependency")
    protected List<ArtifactDependency> artifactDependencies;
    @XmlElement(name = "artifact")
    protected List<Artifact> artifacts;
    @XmlElement(name = "variabilityPoint")
    protected List<VariabilityPoint> variabilityPoints;
    protected Description description;
    @XmlElement(name = "artifactType")
    protected List<ArtifactType> artifactTypes;
    protected Reference reference;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected String type;
    @XmlAttribute
    protected String version;
    @XmlAttribute
    protected String digestName;
    @XmlAttribute
    protected String digestValue;
    @XmlAttribute
    protected String accessRights;

    /**
     * Gets the value of the artifactContexts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifactContexts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifactContexts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArtifactContext }
     * 
     * 
     */
    public List<ArtifactContext> getArtifactContexts() {
        if (artifactContexts == null) {
            artifactContexts = new ArrayList<ArtifactContext>();
        }
        return this.artifactContexts;
    }

    /**
     * Gets the value of the artifactDependencies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifactDependencies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifactDependencies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArtifactDependency }
     * 
     * 
     */
    public List<ArtifactDependency> getArtifactDependencies() {
        if (artifactDependencies == null) {
            artifactDependencies = new ArrayList<ArtifactDependency>();
        }
        return this.artifactDependencies;
    }

    /**
     * Gets the value of the artifacts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifacts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifacts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Artifact }
     * 
     * 
     */
    public List<Artifact> getArtifacts() {
        if (artifacts == null) {
            artifacts = new ArrayList<Artifact>();
        }
        return this.artifacts;
    }

    /**
     * Gets the value of the variabilityPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the variabilityPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVariabilityPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VariabilityPoint }
     * 
     * 
     */
    public List<VariabilityPoint> getVariabilityPoints() {
        if (variabilityPoints == null) {
            variabilityPoints = new ArrayList<VariabilityPoint>();
        }
        return this.variabilityPoints;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link Description }
     *     
     */
    public Description getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link Description }
     *     
     */
    public void setDescription(Description value) {
        this.description = value;
    }

    /**
     * Gets the value of the artifactTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifactTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifactTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArtifactType }
     * 
     * 
     */
    public List<ArtifactType> getArtifactTypes() {
        if (artifactTypes == null) {
            artifactTypes = new ArrayList<ArtifactType>();
        }
        return this.artifactTypes;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getReference() {
        return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setReference(Reference value) {
        this.reference = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the digestName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestName() {
        return digestName;
    }

    /**
     * Sets the value of the digestName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestName(String value) {
        this.digestName = value;
    }

    /**
     * Gets the value of the digestValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDigestValue() {
        return digestValue;
    }

    /**
     * Sets the value of the digestValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDigestValue(String value) {
        this.digestValue = value;
    }

    /**
     * Gets the value of the accessRights property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessRights() {
        return accessRights;
    }

    /**
     * Sets the value of the accessRights property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessRights(String value) {
        this.accessRights = value;
    }

}
