//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 12:55:41 AM BRST 
//


package br.ufrgs.inf.ras.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * xmi:ordered=false
 * 
 * property order is (these are role names)
 *  1. artifactActivity
 *  2. contextRef
 *  3. assetActivity
 * 
 * <p>Java class for Usage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Usage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contextRef" type="{http://defaultprofile.ecore}ContextRef" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="artifactActivity" type="{http://defaultprofile.ecore}ArtifactActivity" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="assetActivity" type="{http://defaultprofile.ecore}AssetActivity" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="artifact" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Usage", propOrder = {
    "contextReves",
    "artifactActivities",
    "assetActivities"
})
@XmlRootElement(name = "Usage")
public class Usage {

    @XmlElement(name = "contextRef")
    protected List<ContextRef> contextReves;
    @XmlElement(name = "artifactActivity")
    protected List<ArtifactActivity> artifactActivities;
    @XmlElement(name = "assetActivity")
    protected List<AssetActivity> assetActivities;
    @XmlAttribute
    protected String artifact;

    /**
     * Gets the value of the contextReves property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contextReves property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContextReves().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContextRef }
     * 
     * 
     */
    public List<ContextRef> getContextReves() {
        if (contextReves == null) {
            contextReves = new ArrayList<ContextRef>();
        }
        return this.contextReves;
    }

    /**
     * Gets the value of the artifactActivities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artifactActivities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getArtifactActivities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArtifactActivity }
     * 
     * 
     */
    public List<ArtifactActivity> getArtifactActivities() {
        if (artifactActivities == null) {
            artifactActivities = new ArrayList<ArtifactActivity>();
        }
        return this.artifactActivities;
    }

    /**
     * Gets the value of the assetActivities property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assetActivities property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetActivities().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetActivity }
     * 
     * 
     */
    public List<AssetActivity> getAssetActivities() {
        if (assetActivities == null) {
            assetActivities = new ArrayList<AssetActivity>();
        }
        return this.assetActivities;
    }

    /**
     * Gets the value of the artifact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtifact() {
        return artifact;
    }

    /**
     * Sets the value of the artifact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtifact(String value) {
        this.artifact = value;
    }

}
