//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.11.14 at 12:55:41 AM BRST 
//


package br.ufrgs.inf.ras.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VariabilityPointBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VariabilityPointBinding">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="bindingRule" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="variabilityPoint" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VariabilityPointBinding")
@XmlRootElement(name = "VariabilityPointBinding")
public class VariabilityPointBinding {

    @XmlAttribute
    protected String bindingRule;
    @XmlAttribute
    protected String variabilityPoint;

    /**
     * Gets the value of the bindingRule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBindingRule() {
        return bindingRule;
    }

    /**
     * Sets the value of the bindingRule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBindingRule(String value) {
        this.bindingRule = value;
    }

    /**
     * Gets the value of the variabilityPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVariabilityPoint() {
        return variabilityPoint;
    }

    /**
     * Sets the value of the variabilityPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVariabilityPoint(String value) {
        this.variabilityPoint = value;
    }

}
